spring:
  datasource:
    url: jdbc:mysql://mysql_server:3306/watered_plants?useSSL=false
    username: root
    password: damr.1992
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true

aws_access_key: ${AWS_ACCESS_KEY}
aws_secret_key: ${AWS_SECRET_ACCESS_KEY}